#############################################################################
# AWS ElasticBeanstalk Host Manager
# Copyright 2011 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Amazon Software License (the “License”). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
# http://aws.amazon.com/asl/
#
# or in the “license” file accompanying this file. This file is
# distributed on an “AS IS” BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, express or implied. See the License for the specific
# language governing permissions and limitations under the License.
#

#
# Host Manager thin configuration
#

---
environment: development
chdir: /opt/elasticbeanstalk/srv/hostmanager
address: 0.0.0.0
user: elasticbeanstalk
group: elasticbeanstalk
port: 8999
pid: /opt/elasticbeanstalk/var/state/hostmanager.pid
rackup: /opt/elasticbeanstalk/srv/hostmanager/config/config.ru
log: /opt/elasticbeanstalk/var/log/hostmanager.log
max_conns: 512
timeout: 30
max_presistent_conns: 256
daemonize: true
